Repository ametnes/nesis, pull requests merged in 2024-04, with the labels that each got.

#61 feat(frontend)(api): add sharepoint datasoure
  docs/src/dev-guide/local.md
  nesis/api/core/config.py
  nesis/api/core/document_loaders/sharepoint.py
  nesis/api/core/tasks/document_management.py
  nesis/api/tests/core/document_loaders/conftest.py
  nesis/api/tests/core/document_loaders/test_sharepoint.py
  nesis/api/tests/tasks/test_document_management.py
  nesis/frontend/client/src/pages/Settings/Datasources/DatasourcesDetailPage.js
Labels: enhancement

#62 chore(docs): update README.md with k8s deployment link
  README.md
Labels: documentation

#63 chore(docs): update testing Nesis helm deployment ports
  docs/src/installing/helm.md
Labels: documentation

#66 build(packaging): run workflow dispatch on tags
  .github/workflows/package.yml
Labels: build
